version: '3.3'

services:
  pgdb:
    image: postgres:latest
    hostname: postgres
    container_name: identity_database
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=identity_database
    ports:
      - "5432:5432"
    volumes:
      - db-postgres:/var/lib/postgresql/data

  identity-service:
    container_name: identity-service
    build:
      context: .
    restart: always
    environment: 
      - POSTGRES_SERVER=pgdb
    depends_on:
      - pgdb

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - identity-service
volumes:
  db-postgres: