name: 'Deploy to EC2'

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Deploy to EC2
              env:
                KEY: ${{ secrets.SSH_KEY }}
                HOST: ${{ secrets.INSTANCE_URL }}
                BRANCH: ${{ github.ref_name }}
                SSH_AUTH_SOCK: /tmp/ssh_agent.sock
              run: |
                mkdir -p /home/runner/.ssh/
                ssh-keyscan $HOST >> /home/runner/.ssh/known_hosts
                echo "$KEY" > /home/runner/.ssh/key.pem
                chmod 700 /home/runner/.ssh/key.pem
                ssh-agent -a $SSH_AUTH_SOCK > /dev/null	
                ssh-add /home/runner/.ssh/key.pem
                ssh -i /home/runner/.ssh/key.pem -T ec2-user@$HOST << EOL
                cd piperoni-identity-service
                git checkout $BRANCH
                git pull
                sudo docker-compose down
                sudo docker-compose build --no-cache
                sudo docker-compose up -d
                EOL
                sleep 2 && curl -X 'GET' "http://$HOST/reset" -H 'accept: application/json'
              